version: 0.2

env:
  variables:
    ING_TEMPLATES: |
      resource.yaml
      
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - mkdir build-output
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
