version: 0.2

env:
  variables:
    S3_ARTIFACT_BUCKET_DEV: joey-ssense-2
    ING_TEMPLATES: |
      sns.yaml
      sqs.yaml
      s3.yaml
      
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - mkdir build-output
      - cp -R etl/deployment/*.yaml build-output
      - for ing_template in $ING_TEMPLATES; 
         do
          aws s3 cp build-output/$ing_template "s3://${S3_ARTIFACT_BUCKET_DEV}/cmi-codebuild-dev/";
        done
  post_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      
artifacts:
  files:
    - 'build-output/root-stack.yaml'
