version: 0.2

env:
  variables:
    S3_ARTIFACT_BUCKET_DEV: cmi-artifacts-dev
    ING_TEMPLATES: |
      s3.yaml
      
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - mkdir build-output
  post_build:
    commands:
      - echo Build completed on `date`

