AWSTemplateFormatVersion: "2010-09-09"
Description: initial yaml file for ssense

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: joey-c-test-bucket-dev
