AWSTemplateFormatVersion: '2010-09-09'
Description: Model and provision AWS CodePipeline and AWS CodeBuild

Parameters:

  EnvironmentType:
    Description: Environment Type
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - qa
      - prod


  ArtifactsBucket:
    Type: String
    Description: artifacts bucket
    Default: rax-ah-ssense-artifacts

  # *** The owner of the Github repo for this application.
  GitHubOwner:
    Type: String
    Default: jcourseault-tc
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: jc-rax-test
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: cicd-dev
    AllowedPattern: "[A-Za-z0-9-]+"



  Cloudwatchlogs:
    Description: 'cloud watch logs for code pipeline'
    Type: String
    Default: '/ssense/pipeline/*' 


Resources:


  DeploymentPipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'deployment-pipeline-${EnvironmentType}-topic'
      Subscription:
      - Endpoint: ahmad.haggag@rackspace.com
        Protocol: email

  # CodePipeline
  GlueJobsCodePipeline: 
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: !Sub DeployGlueJobsPipeline-${AWS::StackName}
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore: 
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages: 
      - 
        Name: Source
        Actions: 
        - 
          Name: GitHubSourceAction
          ActionTypeId: 
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: "1"
          OutputArtifacts: 
            - Name: SourceOutput
          Configuration: 
              Owner: !Ref GitHubOwner
              Repo: !Ref GitHubRepo
              Branch: !Ref GitHubBranch
              PollForSourceChanges: true 
              OAuthToken: '{{resolve:secretsmanager:MyGitHubSecret:SecretString:token}}'
          RunOrder: 1
      -
        Name: BuildGlueJobs
        Actions:
        -
          Name: BuildGlueJobsStack
          ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: "1"
          InputArtifacts:
            - Name: SourceOutput
          OutputArtifacts:
            - Name: BuildArtifacts
          Configuration:
            ProjectName: !Ref SsenseCodeBuild
          RunOrder: 2

      -
        Name: QA_Deployment_Approval
        Actions:
        -
          Name: QA_Deployment_Approval
          InputArtifacts: []
          ActionTypeId:
             Category: Approval
             Owner: AWS
             Provider: Manual
             Version: "1"
          Configuration:
            NotificationArn: !Ref DeploymentPipelineSNSTopic
            CustomData: "Please Provide Required Action for QA Deployment "
          RunOrder: 3
        -
          Name: QA_Deployment
          InputArtifacts:
            - Name: BuildArtifacts
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: "CloudFormation"
            Version: '1'
          Configuration:
            ActionMode: CREATE_UPDATE
            StackName: !Sub ssense-glue-jobs-qc-stack
            ParameterOverrides: !Sub  '{"EnvironmentType": "qa","ArtifactsBucket": "${ArtifactsBucket}" }'
            TemplatePath:  BuildArtifacts::build-output/glue-cfn.yaml
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: !GetAtt CodePipelineRole.Arn
          RunOrder: 4

      -
        Name: PROD_Deployment_Approval
        Actions:
        -
          Name: PROD_Deployment_Approval
          InputArtifacts: []
          ActionTypeId:
             Category: Approval
             Owner: AWS
             Provider: Manual
             Version: "1"
          Configuration:
            NotificationArn: !Ref DeploymentPipelineSNSTopic
            CustomData: "Please Provide Required Action for PROD Deployment "
          RunOrder: 3
        -
          Name: QA_Deployment
          InputArtifacts:
            - Name: BuildArtifacts
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: "CloudFormation"
            Version: '1'
          Configuration:
            ActionMode: CREATE_UPDATE
            StackName: !Sub ssense-glue-jobs-prod-stack
            ParameterOverrides: !Sub  '{"EnvironmentType": "prod", "ArtifactsBucket": "${ArtifactsBucket}" }'
            TemplatePath: BuildArtifacts::build-output/glue-cfn.yaml
            Capabilities: CAPABILITY_NAMED_IAM
            RoleArn: !GetAtt CodePipelineRole.Arn
          RunOrder: 4


  # CodeBuild
  SsenseCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub BuildGlueJobsStack-${AWS::StackName}
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        BuildSpec: glue-buildspec.yaml
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: True
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: ARTIFACTS_BUCKET
            Value: !Ref ArtifactsBucket
          - Name: ENV_TYPE
            Value: !Ref EnvironmentType
      LogsConfig: 
        CloudWatchLogs:
          Status: ENABLED


  # IAM Roles & Policies
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodePipeline-Role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: 
               - codepipeline.amazonaws.com
               - cloudformation.amazonaws.com
      Path: /
      Policies:
        - PolicyName: !Sub CodePipeline-Policy-${AWS::StackName}
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:*
                  - codebuild:*
                  - codedeploy:*
                  - cloudformation:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
 
      

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuild-Role-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: !Sub CodeBuild-Policy-${AWS::StackName}
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - cloudwatch:*
                  - codebuild:*
                  - glue:*
                  - s3:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'


  # AppPipelineWebhook:
  #   Type: 'AWS::CodePipeline::Webhook'
  #   Properties:
  #     Name: AppPipelineWebhook
  #     Authentication: GITHUB_HMAC
  #     AuthenticationConfiguration:
  #       SecretToken: '{{resolve:secretsmanager:MyGitHubSecret:SecretString:token}}'
  #     Filters:
  #       - JsonPath: $.ref
  #         MatchEquals: 'refs/heads/{Branch}'
  #     TargetPipeline: !Ref GlueJobsCodePipeline
  #     TargetAction: GitHubSourceAction
  #     TargetPipelineVersion: !GetAtt 
  #       - GlueJobsCodePipeline
  #       - Version
  #     RegisterWithThirdParty: true
                

  